version: '3'
name: {$project_name}

services:
  {$project_name}:
    image: {$project_name}
    container_name: {$project_name}
    ports:
      - "2112:80"
    environment:
      HY_INSTANCE_NAME: {$project_name} development container
      HY_MONGO_HOST: {$project_name}-mongo
      HY_API_PORT: 80
      HY_CACHE_CONTROL: no-cache, no-store, must-revalidate
      HY_CACHE_EXPIRES: 30
    volumes:
    - ./logging:/var/log/{$project_name}
    depends_on:
      - {$project_name}-mongo

  {$project_name}-mongo:
    image: mongo
    container_name: {$project_name}-mongo
    volumes:
      - {$project_name}-mongodb:/data/db
      - {$project_name}-mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
     {$project_name}-mongodb:
     {$project_name}-mongodb_config:
