#!/usr/bin/env bash
if [ "$#" -lt 1 ]; then
    echo "Please provide a version number, e.g. ./image-build 1.0.0"
    exit
fi

REPOS={$project_name}
docker build -t $REPOS:latest .

LATESTIMAGE=$(docker images $REPOS:latest --quiet)
docker tag $LATESTIMAGE $REPOS:$1

# if [ "$2" == "y" ]; then
#     ./image-push $1
# fi
