# https://just-the-docs.com/

title: hypermea
email: michael@pointw.com
logo: /assets/img/hypermea.png
# favicon_ico: 
description: >- 
  Simple Commands, Serious APIs.

port: 4001

theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tabs

color_scheme: dark
